[package]
authors = ['Parallel Team']
edition = '2018'
name    = 'pallet-loans-benchmarking'
version = '3.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec              = { package = 'parity-scale-codec', version = '2.0.0', default-features = false }
frame-benchmarking = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', default-features = false, version = '3.0.0' }
frame-support      = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', default-features = false, version = '3.0.0' }
frame-system       = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', default-features = false, version = '3.0.0' }
orml-currencies    = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', default-features = false }
orml-oracle        = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', default-features = false }
orml-tokens        = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', default-features = false }
orml-traits        = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', default-features = false }
pallet-balances    = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', version = '3.0.0', default-features = false }
pallet-loans       = { default-features = false, features = ['runtime-benchmarks'], path = '../../loans' }
pallet-prices      = { path = '../../../pallets/prices', default-features = false }
primitives         = { package = 'parallel-primitives', path = '../../../primitives', default-features = false }
sp-runtime         = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', version = '3.0.0', default-features = false }
sp-std             = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', version = '3.0.0', default-features = false }

[dev-dependencies]
pallet-timestamp = { git = 'https://github.com/paritytech/substrate.git', version = '3.0.0', branch = 'polkadot-v0.9.8', default-features = false }
sp-core          = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', version = '3.0.0', default-features = false }
sp-io            = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.8', version = '3.0.0', default-features = false }

[features]
default = ['std']
std     = [
  'codec/std',
  'frame-benchmarking/std',
  'frame-support/std',
  'frame-system/std',
  'orml-currencies/std',
  'orml-oracle/std',
  'orml-tokens/std',
  'orml-traits/std',
  'pallet-balances/std',
  'primitives/std',
  'pallet-loans/std',
  'pallet-prices/std',
  'primitives/std',
  'sp-runtime/std',
  'sp-std/std',
]
