[package]
authors = ['Parallel Team']
edition = '2018'
name    = 'pallet-staking'
version = '1.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec            = { package = 'parity-scale-codec', version = '2.0.0', default-features = false }
frame-support    = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.1', default-features = false, version = '3.0.0' }
frame-system     = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.1', default-features = false, version = '3.0.0' }
orml-currencies  = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', default-features = false }
orml-tokens      = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', default-features = false }
orml-traits      = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', default-features = false }
orml-utilities   = { git = 'https://github.com/open-web3-stack/open-runtime-module-library.git', default-features = false }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.1', default-features = false, version = '3.0.0' }
primitives       = { package = 'parallel-primitives', path = '../../primitives', default-features = false }
serde            = { version = '1', features = ['derive'] }
sp-runtime       = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.1', version = '3.0.0', default-features = false }
sp-std           = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.1', version = '3.0.0', default-features = false }

[dev-dependencies]
pallet-balances = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.1', default-features = false, version = '3.0.0' }
serde           = { version = '1' }
sp-core         = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.1', default-features = false, version = '3.0.0' }
sp-io           = { git = 'https://github.com/paritytech/substrate.git', branch = 'polkadot-v0.9.1', default-features = false, version = '3.0.0' }

[features]
default = ['std']
std     = [
  'codec/std',
  'frame-support/std',
  'frame-system/std',
  'orml-currencies/std',
  'orml-tokens/std',
  'orml-traits/std',
  'orml-utilities/std',
  'pallet-timestamp/std',
  'primitives/std',
  'sp-runtime/std',
  'sp-std/std',
]
